config/routes.rb
Rails.application.routes.draw do
  resources :movies

  resources :actors

  
  root 'movies#new'

  get 'game', to: 'static_pages#game'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
	belongs_to :movie

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :actors, dependent: :destroy
	after_create :fill_actors_table
	validates_presence_of :title

	def fill_actors_table
	  movie_list = Imdb::Search.new(title)

	  #automatically just goes for the first movie if there are movies with the same name cuz it's a feature. 
	  new_movie = movie_list.movies.first 
	  id = new_movie.id
	  self.imdb_id = id
	  self.save
	  
	  i = Imdb::Movie.new("#{id}")
	  i.cast_members.each do |actor_name|
	    actor_image = Google::Search::Image.new(:query => actor_name, :image_size => :medium).first
		actor_image_url = actor_image.uri
	  	actor =  self.actors.build(:name => actor_name, :file => actor_image_url)
	  	actor.save
	  end
	end

	def find_random_actors
		self.actors.order("RANDOM()").first(5)	
	end

end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Actor was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'Actor was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'Actor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name, :file, :id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @movie = Movie.find(params[:id])
    @actors = @movie.find_random_actors
  end

  # GET /movies/new
  def new
    @movie = Movie.new

  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.find_or_create_by(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title)
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def game
  end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this actor from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.text_field :file %>
  </div>
  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Editing actor</h1>

<%= render 'form' %>

<%= link_to 'Show', @actor %> |
<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<h1>Listing actors</h1>
List instructions here:
Match the name of the actor or actress with their picture! If 


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>File</th>
      <th>Id</th>
      <th>Movie</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.file %></td>
        <td><%= actor.id %></td>
        <td><%= actor.movie_id %></td>

        <td><%= link_to 'Show', actor %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/actors/new.html.erb
<h1>New actor</h1>

<%= render 'form' %>

<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @actor.name %>
</p>

<p>
  <strong>File:</strong>
  <%= @actor.file %>
</p>

<p>
  <strong>Id:</strong>
  <%= @actor.id %>
</p>

<%= link_to 'Edit', edit_actor_path(@actor) %> |
<%= link_to 'Back', actors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paw-parazzi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <%= stylesheet_link_tag "custom.css"%>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <link rel="shortcut icon" type="image/ico" href="http://www.dreamtemplate.com/dreamcodes/web_icons/gray-camera-icon.png" />

</head>
<body>
      <%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => {:class => "form-group"} do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger" role="alert">
      <h4><span class="glyphicon glyphicon-warning-sign"></span>   <%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h4>
      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.label :title, "What movie was he assigned to photograph again?:", class: "control-label" %><br>
    <%= f.text_field :title,  class: "form-control", :placeholder => "ie. The Fast and the Fur-ious, The Purrincess Bride, etc... " %>
    <%= f.submit "Let's Play", class: "btn btn-default center-block" %>  

<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %><xe/td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<div class= "container">
	<div class = "row-centered">
		<h1>Paw-parazzi</h1>
	</div>
	<div class = "row">
		<div class= "col-md-12">
			<img src ="http://pre14.deviantart.net/d844/th/pre/f/2012/123/a/2/cat_as_photographer_by_microkey-d4ydm7b.jpg" class="img-rounded">
		</div>
	</div>
	<div class= "row">
		<div class= "col-md-12">
			<p> Pierre Fox Daguerre the IV is a world famous paw-parazzi. But he has been procrastinating on research for his upcoming assignment! Help Pierre by matching actors' photographs with their names so he knows who to look for and photograph! </p>
		</div>
	</div>

	<div class = "row">
		<div class= "col-md-12">
		<%= render 'form' %>
		<font size='2'> * note: it may take a second for the game to load after you submit a movie. Play with some yarn and wait. </font>
		</div>
	</div>
 </div>

app/views/movies/show.html.erb
<div class= "container">
	<div class = "row-centered">
		<h2>Paw-parazzi</h2>
		<p> Stalking the actors from: <%= @movie.title %></p> 
		<br>		
		<hr>
		<h4>How to play:</h4>
		Match the actors' photos with their names! Yup, it's that easy.
		<hr>

		<div class="alert alert-danger" role="alert"><span class="glyphicon glyphicon-alert"></span><b>  BUT WAIT</b> OMG YOU ONLY HAVE <span id="timer"></span> SECONDS.</div>


 		<% actor_array_json = @actors.to_json %>
 		<% shuffled_actors = @actors.shuffle %>

   		<script type="text/javascript">

    	var actor_array_js = <%= raw @actors.to_json %>

    	function check_answers(){
      		var points = 0;
      		var array_of_forms = []; 
      		for (i = 0; i < actor_array_js.length; i++) {
        		var id = "answer" + i;
    
        		if (actor_array_js[i].id == document.getElementById(id).value){
          			points = points + 1;
        		}
      		}
      		window.location = '/game?points='+points;
    	}
      	</script>

  		<table>
    	<tbody>
      	<form method="post" action="/game">        
       
      	<% iterator = 0 %>
      	<% @actors.each do |iter| %>
	      	<tr>
	        	<td><img src =<%= iter.file %> width = '200px', height = '200px'></td>
	        	<td>
	          		<select id="answer<%= iterator %>" class="form-control">
	            		<% shuffled_actors.each do |person| %>
	              			<option value=<%=person.id %>><%= person.name %></option>
	            		<% end %>

	            		<script type="text/javascript">
	              			<% iterator = iterator + 1 %>
	            		</script> 

	          		</select>
	        	</td>
	       </tr>
  	<% end %>

  	<tr>
    	<td>
     		<input type="button" onclick="check_answers()" value="Submit" class="btn btn-success">
     		<br>
    	</td>
    	<td>
    		<input type="button" onclick="location.reload()" value="Halp! An image didn't load!" class="btn btn-warning">
		</td>
   </tr>

  </tbody>
 </table>
</div>
</div>

<script type="text/javascript">
var count=30;
var counter=setInterval(timer, 1000); //1000 will  run it every 1 second

function timer()
{
  count=count-1;
  if (count <= 0)
  {
     clearInterval(counter);
     check_answers();
     return;
  }

	document.getElementById("timer").innerHTML=count;

}

</script>

app/views/static_pages/game.html.erb
<div class="container">
	<div class="row-centered">
		<div class= "col-md-12">
			<br><br>
			 <script type="text/javascript">
			 var points = location.search.split('points=')[1]
			 if(points < 1){
			 	document.write("<img src='http://cdn0.stocksy.com/a/M84000/z0/15894.jpg' class='img-rounded'><br><p class='center'>You got less than 1 correct. You must have had to try to be this bad.</p> ");
			 }
			 else if (points == 1){
			 	document.write("<img src='http://i.huffpost.com/gen/1043009/images/o-LIL-BUB-AND-FRIENDZ-TRAILER-facebook.jpg' class='img-rounded'><br><p class='center'>You only got 1/5 correct! Poor Pierre is going to get fired. </p>");

			 }
			 else if(points == 2){
			 	document.write("<img src='http://petsadviser.supercopyeditors.netdna-cdn.com/wp-content/uploads/2012/06/why-is-cat-scared-rain-thunder.png' class='img-rounded'> <br> <p class='center'><br>meow. You got 2/5 correct. Pierre barely scraped by.</p> ")
			 }

			 else if (points == 3){
			 	document.write("<img src='http://cdn.petplace.com/images/default-source/Featured-Wide-Large/8746_cats.jpg?sfvrsn=3' class='img-rounded'><br> <p class='center'>You got 3/5 correct. You are incredibly average</p>");
			 }
			 else if (points == 4){
			 	document.write("<img src='https://fuzfeed.com/wp-content/uploads/2015/05/happy_cat_is_happy_by_anarosaphotography-d4ddoh1-640x420.jpg' class='img-rounded'><br><p class='center'> You got 4/5 correct. You are pretty awesome</p>");
			 }
			 else if(points == 5){
			 	document.write("<img src='http://cdn2.hellogiggles.com/wp-content/uploads/2014/08/08/smiling-cat.jpg?123' class='img-rounded'><br><p class='center'>You got 5/5 correct! It's ok. I won't tell everyone how long you spend catching up on celebrity gossip every day!</p>");

			 	console.log("poop");
			 }
			 else{
			 	document.write("<img src='http://i.ytimg.com/vi/Y9TiP9hFTdA/maxresdefault.jpg' class='img-rounded'>")
			 	document.write("<p class='center'>I SEE YOU CHEATING!!!!</p>")
			 }

			 </script>

<br><br><br>
<a href="/"><input type="button" onclick="" value="One moar tiiiiiiime" class="btn btn-default"></a>
<br>

		</div>
	</div>
</div>

app/views/static_pages/index.html.erb
<div class="container-fluid">
	<div class="row">
  		<div class="col-md-6 col-sm-offset-4">
			<h1>Hello, world!</h1>
			<blockquote>
  				<p>This game is just so awesome! I'm going to play it forever.</p>
  				<footer>Someone famous in <cite title="Source Title">Source Title</cite></footer>
			</blockquote>

			<h3>Instructions</h3> 
			01. Put 
			02. profit.
			<a href='/movies/new'>
			<button type="button" class="btn btn-default" aria-label="Left Align">
 			<span class="glyphicon glyphicon-play" aria-hidden="true"></span>
				Ok, I'm curious.
			</button></a>

		</div>
	</div>
</div>